
version: '2.1'
services:
  jenkins-swarm-slave:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR:-mirrors.163.com}

      - IMAGE_ARG_ENCODING=${IMAGE_ARG_ENCODING:-UTF-8}
      - IMAGE_ARG_JAVA_OPTS=${IMAGE_ARG_JAVA_OPTS}
      - IMAGE_ARG_LANGUAGE=${IMAGE_ARG_LANGUAGE:-en}
      - IMAGE_ARG_LOCALE=${IMAGE_ARG_LOCALE:-en_US}
      - IMAGE_ARG_REGION=${IMAGE_ARG_REGION:-US}
      #- IMAGE_ARG_TZ=${IMAGE_ARG_TZ:-UTC+8:00}
      - IMAGE_ARG_TZ_AREA=${IMAGE_ARG_TZ_AREA:-Etc}
      - IMAGE_ARG_TZ_ZONE=${IMAGE_ARG_TZ_ZONE:-UTC}

      - IMAGE_ARG_USER=${IMAGE_ARG_USER:-ubuntu}
      - IMAGE_ARG_VERSION=${IMAGE_ARG_VERSION:-3.14}
    #command: ["-username", "slave", "-password", "slave_pass", "-executors", "3"]
    command: ${JENKINS_SWARN_SLAVE_COMMAND:--username slave -password slave_pass -executors 3}
    container_name: ${CONTAINER_HOST_NAME:-jenkins-swarm-slave}
    environment:
    - CI_INFRA_OPT_GIT_AUTH_TOKEN=${CI_INFRA_OPT_GIT_AUTH_TOKEN:-your_CI_INFRA_OPT_GIT_AUTH_TOKEN}
    - JENKINS_PORT_8080_TCP_ADDR=${JENKINS_PORT_8080_TCP_ADDR:-jenkins}
    - JENKINS_PORT_8080_TCP_PORT=${JENKINS_PORT_8080_TCP_PORT:-8080}

    #external_links:
    #- jenkins:jenkins
    #- nexus:nexus3
    #- mvnsite:mvnsite
    hostname: ${CONTAINER_HOST_NAME:-jenkins-swarm-slave}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-jenkins-swarm-slave}:${IMAGE_TAG:-3.14-en_US.UTF-8_Etc.UTC-bionic}
    networks:
      local-network:
        ipv4_address: 172.16.238.36
        #ipv6_address: 2001:3984:3989::36
    restart: always
    volumes:
    - data:/home/${IMAGE_ARG_USER:-ubuntu}
    - /var/run/docker.sock:/var/run/docker.sock


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
